services:
  nutrifood-api:
    build: ./backend
    container_name: nutrifood-api
    restart: unless-stopped
    volumes:
      - ./data:/data
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - DB_PATH=/data/nutrifood.db
      - JWT_SECRET=4d94b004390976e65097c4adbb4e34da6ff1d02ae329cdc2c16beb8ba6db0eb2
      - JWT_EXPIRY_HOURS=2160
      # Email (SMTP)
      - SMTP_HOST=smtp.fastmail.com
      - SMTP_PORT=465
      - SMTP_USER=ai@slopvibe.org
      - SMTP_PASS=3q6q6a76769d6r5c
      - MAIL_FROM=ai@slopvibe.org
      - APP_URL=https://slopvibe.org/nutri-food/

  nutrifood-web:
    build: ./web
    container_name: nutrifood-web
    restart: unless-stopped
    ports:
      - "5011:80"
    volumes:
      - ./config:/usr/share/nginx/html
    depends_on:
      - nutrifood-api
