sonar.projectKey=nutri-food
sonar.projectName=NutriFood
sonar.sources=backend,web/js
sonar.language=py,js
sonar.python.version=3.13
sonar.host.url=http://10.81.69.110:9000
sonar.login=sqp_9d31f321bc23dca3464ae545bb3dd7cab189c125
sonar.exclusions=**/node_modules/**,**/.venv/**,**/__pycache__/**,backend/tests/**,**/*.min.js
