sonar.projectKey=nutri-food
sonar.projectName=NutriFood
sonar.sources=.
sonar.exclusions=node_modules/**,**/*.pyc,__pycache__/**,docs/**,.git/**
sonar.javascript.file.suffixes=.js,.html
sonar.python.file.suffixes=.py
sonar.html.file.suffixes=.html
