sonar.projectKey=nutri-food
sonar.projectName=NutriFood
sonar.sources=.
sonar.exclusions=node_modules/**,**/*.pyc,__pycache__/**,docs/**,.git/**,.scannerwork/**,web/defaults/**
sonar.javascript.file.suffixes=.js
sonar.python.file.suffixes=.py
sonar.html.file.suffixes=.html
