services:
  nutrifood-api:
    build: .
    container_name: nutrifood-api
    restart: unless-stopped
    ports:
      - "5010:5000"
    volumes:
      - ./data:/data
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - DB_PATH=/data/nutrifood.db
      - JWT_SECRET=6053e105b879b1070189b78b70acf669e79b6522314b36ae50477d06f4131a01
      - JWT_EXPIRY_HOURS=2160
